services:
  geoip: 
    image: yavabit/geoip-service
    build:
      dockerfile: geoip.dockerfile
  server: 
    image: yavabit/geotime
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - geoip